version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ./app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - ./app:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./tmp/grafana-volume:/var/lib/grafana

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_USER_PASSWORD: password
      INFLUXDB_ADMIN_USER: telegraf
      INFLUXDB_ADMIN_PASSWORD: pag ssword
      INFLUXDB_USER: telegraf
    ports:
      - 8086:8086
    volumes:
      - ./tmp/influxdb-volume:/var/lib/influxdb

  telegraf:
    image:  telegraf
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock